function plot_input_hist( data_set, varargin )
% Plot the data structure. If a string is given the data structure is
% loaded from the file it points to.
%

    [ x_neurons, ...
      lbls, ...
      colors, ...
      pat_labels, ...
      plot_axis, ...
      hist_axis, ...
      run_id, ...
      seq_id, ...
      hold_it, ...
      set_name ] = snn_process_options( varargin, ...
                                        'idx_neurons', 1:20, ...
                                        'neuron_labels', [], ...
                                        'colors', [], ...
                                        'pat_labels', [], ...
                                        'plot_axis', [], ...
                                        'hist_axis', [], ...
                                        'run_id', 1, ...
                                        'seq_id', 1, ...
                                        'hold', 'off', ...
                                        'set_name', 'sim_test' );

                                    
    if isempty(colors)
        if isfield(data_set,'colors')
            colors = data_set.colors;
        else
            colors = snn_options( 'colors' );
        end
    end

%% prepare data for plotting    

    if (run_id > 1) && (size(data_set.(set_name),2) == 1)
        sim_data = data_set.(set_name){seq_id}(run_id);
    else
        sim_data = data_set.(set_name){seq_id,run_id};
    end

    Lt = sim_data.Lt;
    Xt = sim_data.Xt;
    
    x_idx = any( repmat(Lt(1,:),length(x_neurons),1) == repmat( x_neurons', 1, size(Lt,2)), 1 );
    
    id2idx = zeros(1,max(x_neurons));
    id2idx(x_neurons) = 1:length(x_neurons);

    n_id = id2idx( Lt(1,x_idx) );
    
    Lt = [ n_id; Lt(2,x_idx); Lt(3,x_idx) ];
    Xt = [ Xt(1,x_idx); Xt(2,x_idx) ];
    sim_data.Lt = Lt;
    sim_data.Xt = Xt;
    sim_data.Lt_y_range = 1:length(x_neurons);

    snn_plot( sim_data, '[Lt[sctl] ]', ...
              'axis', plot_axis, 'numbering', 'none', 'colors', colors, ...
              'show_titles', false, 'hold', hold_it );
                                          
                                          
    if hist_axis
        axes( hist_axis );
        sorted_hist_plot( sim_data, data_set.net.num_neurons, x_neurons, 'Xt' );
        set( gca, 'LineWidth', 0.8, 'FontName', snn_options( 'FontName' ), ...
                  'FontSize', snn_options( 'FontSize' ), ...
                  'YTick', [0.5, length(x_neurons)+0.5], ...
                  'YTickLabel', {'1',num2str(length(x_neurons))}, ...
                  'YTickMode', 'manual', 'YTickLabelMode', 'manual' );
    end    
end
